name: CI

on:
  - push
  - pull_request

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - double: aarch64-linux
            runner: ubuntu-24.04-arm
            flake: sharpSAT-static
          - double: x86_64-linux
            runner: ubuntu-24.04
            flake: sharpSAT-static
          - double: aarch64-darwin
            runner: macos-15
            flake: sharpSAT-static
          - double: x86_64-darwin
            runner: macos-13
            flake: sharpSAT-static
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: cachix/install-nix-action@v30
      - name: Build
        run: nix build -L .#${{ matrix.target.flake }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sharpSAT-${{ matrix.target.double }}
          path: result
